SELECT
  i.TYPE_CONTRAT AS typeContrat,
  d.ANNEE AS annee,
  COUNT(*) AS total
FROM INDIVIDU i
INNER JOIN DOSSIER d ON i.ID_INDIVIDU = d.ID_INDIVIDU
WHERE (i.STATUT = 'ACTIF' AND i.DATE_SUPPRESSION IS NULL AND d.ANNEE BETWEEN 2020 AND 2024)
GROUP BY i.TYPE_CONTRAT, d.ANNEE
HAVING COUNT(*) > 10
ORDER BY d.ANNEE DESC, i.TYPE_CONTRAT ASC
LIMIT 100